name: Build Assets
on: [push]
jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: CMake x64
        shell: pwsh
        run: cmake -G "Visual Studio 17 2022" -A x64 CMakeLists.txt -B x64

      - name: Build x64
        shell: pwsh
        run: cmake --build x64 --target Multi-Segmenter Multi-Segmenter-Test --config Release && mv x64/Release/* x64

      - name: Install requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        working-directory: utils/SimpleRenderer
        run: pip install -r requirements.txt

      - name: Test launch
        shell: pwsh
        run: x64/Multi-Segmenter.exe assets/Cube_noised.obj

      - name: Run
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        run: python utils/SimpleRenderer/renderer.py assets/Segmented_Cube_noised.obj

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            assets/Segmented_Cube_noised.obj
            assets/Segmented_Cube_noised_x_axis.mp4
            assets/Segmented_Cube_noised_y_axis.mp4
            assets/Segmented_Cube_noised_z_axis.mp4
