on:
  workflow_call:
jobs:
  build:
    name: Build Project (Windows)
    runs-on: windows-lab
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: CMake x64
        shell: pwsh
        run: cmake -G "Visual Studio 17 2022" -A x64 CMakeLists.txt -B Windows

      - name: Build x64
        shell: pwsh
        run: cmake --build Windows --target Multi-Segmenter Multi-Segmenter-Test --config Release && mv Windows/Release/* Windows

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            Windows/Multi-Segmenter.exe
            Windows/Multi-Segmenter-Test.exe